/*
 * generated by Xtext
 */
package ausim.xtext.kanban.domainmodel.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import ausim.xtext.kanban.domainmodel.ui.internal.KanbanmodelActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KanbanmodelExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return KanbanmodelActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return KanbanmodelActivator.getInstance().getInjector(KanbanmodelActivator.AUSIM_XTEXT_KANBAN_DOMAINMODEL_KANBANMODEL);
	}
	
}
