/*
* generated by Xtext
*/
package ausim.xtext.kanban.domainmodel.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KanbanmodelAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("ausim/xtext/kanban/domainmodel/parser/antlr/internal/InternalKanbanmodel.tokens");
	}
}
