/*
 * generated by Xtext
 */
package ausim.xtext.kanban.domainmodel;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class KanbanmodelRuntimeModule extends ausim.xtext.kanban.domainmodel.AbstractKanbanmodelRuntimeModule {

}
