/*
 * generated by Xtext
 */
package ausim.xtext.kanban.domainmodel.serializer;

import ausim.xtext.kanban.domainmodel.kanbanmodel.Asset;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Capability;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Causality;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Command;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Entity;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Event;
import ausim.xtext.kanban.domainmodel.kanbanmodel.KanbanSchedulingSystem;
import ausim.xtext.kanban.domainmodel.kanbanmodel.KanbanTaskModel;
import ausim.xtext.kanban.domainmodel.kanbanmodel.KanbanmodelPackage;
import ausim.xtext.kanban.domainmodel.kanbanmodel.LocalValue;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Mechanism;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Provision;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Requirement;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Resource;
import ausim.xtext.kanban.domainmodel.kanbanmodel.ResourceAllocation;
import ausim.xtext.kanban.domainmodel.kanbanmodel.ResourceOutsourcing;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Service;
import ausim.xtext.kanban.domainmodel.kanbanmodel.ServiceProvider;
import ausim.xtext.kanban.domainmodel.kanbanmodel.ServiceType;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Skill;
import ausim.xtext.kanban.domainmodel.kanbanmodel.State;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Statemachine;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Strategy;
import ausim.xtext.kanban.domainmodel.kanbanmodel.TaskPattern;
import ausim.xtext.kanban.domainmodel.kanbanmodel.TaskType;
import ausim.xtext.kanban.domainmodel.kanbanmodel.Transition;
import ausim.xtext.kanban.domainmodel.kanbanmodel.ValueFunction;
import ausim.xtext.kanban.domainmodel.kanbanmodel.WIAcceptance;
import ausim.xtext.kanban.domainmodel.kanbanmodel.WIAssignment;
import ausim.xtext.kanban.domainmodel.kanbanmodel.WISelection;
import ausim.xtext.kanban.domainmodel.kanbanmodel.WorkItem;
import ausim.xtext.kanban.domainmodel.kanbanmodel.WorkSource;
import ausim.xtext.kanban.domainmodel.services.KanbanmodelGrammarAccess;
import com.google.inject.Inject;
import com.google.inject.Provider;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.serializer.acceptor.ISemanticSequenceAcceptor;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.diagnostic.ISemanticSequencerDiagnosticProvider;
import org.eclipse.xtext.serializer.diagnostic.ISerializationDiagnostic.Acceptor;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.GenericSequencer;
import org.eclipse.xtext.serializer.sequencer.ISemanticNodeProvider.INodesForEObjectProvider;
import org.eclipse.xtext.serializer.sequencer.ISemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class KanbanmodelSemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private KanbanmodelGrammarAccess grammarAccess;
	
	@Override
	public void createSequence(EObject context, EObject semanticObject) {
		if(semanticObject.eClass().getEPackage() == KanbanmodelPackage.eINSTANCE) switch(semanticObject.eClass().getClassifierID()) {
			case KanbanmodelPackage.ASSET:
				sequence_Asset(context, (Asset) semanticObject); 
				return; 
			case KanbanmodelPackage.CAPABILITY:
				sequence_Capability(context, (Capability) semanticObject); 
				return; 
			case KanbanmodelPackage.CAUSALITY:
				sequence_Causality(context, (Causality) semanticObject); 
				return; 
			case KanbanmodelPackage.COMMAND:
				sequence_Command(context, (Command) semanticObject); 
				return; 
			case KanbanmodelPackage.ENTITY:
				sequence_Entity(context, (Entity) semanticObject); 
				return; 
			case KanbanmodelPackage.EVENT:
				sequence_Event(context, (Event) semanticObject); 
				return; 
			case KanbanmodelPackage.KANBAN_SCHEDULING_SYSTEM:
				sequence_KanbanSchedulingSystem(context, (KanbanSchedulingSystem) semanticObject); 
				return; 
			case KanbanmodelPackage.KANBAN_TASK_MODEL:
				sequence_KanbanTaskModel(context, (KanbanTaskModel) semanticObject); 
				return; 
			case KanbanmodelPackage.LOCAL_VALUE:
				sequence_LocalValue(context, (LocalValue) semanticObject); 
				return; 
			case KanbanmodelPackage.MECHANISM:
				sequence_Mechanism(context, (Mechanism) semanticObject); 
				return; 
			case KanbanmodelPackage.PROVISION:
				sequence_Provision(context, (Provision) semanticObject); 
				return; 
			case KanbanmodelPackage.REQUIREMENT:
				sequence_Requirement(context, (Requirement) semanticObject); 
				return; 
			case KanbanmodelPackage.RESOURCE:
				sequence_Resource(context, (Resource) semanticObject); 
				return; 
			case KanbanmodelPackage.RESOURCE_ALLOCATION:
				sequence_ResourceAllocation(context, (ResourceAllocation) semanticObject); 
				return; 
			case KanbanmodelPackage.RESOURCE_OUTSOURCING:
				sequence_ResourceOutsourcing(context, (ResourceOutsourcing) semanticObject); 
				return; 
			case KanbanmodelPackage.SERVICE:
				sequence_Service(context, (Service) semanticObject); 
				return; 
			case KanbanmodelPackage.SERVICE_PROVIDER:
				sequence_ServiceProvider(context, (ServiceProvider) semanticObject); 
				return; 
			case KanbanmodelPackage.SERVICE_TYPE:
				sequence_ServiceType(context, (ServiceType) semanticObject); 
				return; 
			case KanbanmodelPackage.SKILL:
				sequence_Skill(context, (Skill) semanticObject); 
				return; 
			case KanbanmodelPackage.STATE:
				sequence_State(context, (State) semanticObject); 
				return; 
			case KanbanmodelPackage.STATEMACHINE:
				sequence_Statemachine(context, (Statemachine) semanticObject); 
				return; 
			case KanbanmodelPackage.STRATEGY:
				sequence_Strategy(context, (Strategy) semanticObject); 
				return; 
			case KanbanmodelPackage.TASK_PATTERN:
				sequence_TaskPattern(context, (TaskPattern) semanticObject); 
				return; 
			case KanbanmodelPackage.TASK_TYPE:
				sequence_TaskType(context, (TaskType) semanticObject); 
				return; 
			case KanbanmodelPackage.TRANSITION:
				sequence_Transition(context, (Transition) semanticObject); 
				return; 
			case KanbanmodelPackage.VALUE_FUNCTION:
				sequence_ValueFunction(context, (ValueFunction) semanticObject); 
				return; 
			case KanbanmodelPackage.WI_ACCEPTANCE:
				sequence_WIAcceptance(context, (WIAcceptance) semanticObject); 
				return; 
			case KanbanmodelPackage.WI_ASSIGNMENT:
				sequence_WIAssignment(context, (WIAssignment) semanticObject); 
				return; 
			case KanbanmodelPackage.WI_SELECTION:
				sequence_WISelection(context, (WISelection) semanticObject); 
				return; 
			case KanbanmodelPackage.WORK_ITEM:
				sequence_WorkItem(context, (WorkItem) semanticObject); 
				return; 
			case KanbanmodelPackage.WORK_SOURCE:
				sequence_WorkSource(context, (WorkSource) semanticObject); 
				return; 
			}
		if (errorAcceptor != null) errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? hasSkills+=Skill*)
	 */
	protected void sequence_Asset(EObject context, Asset semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? reqs+=Requirement+)
	 */
	protected void sequence_Capability(EObject context, Capability semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (triggered+=[WorkItem|ID]+ tProgress=INT? tProbability=INT?)
	 */
	protected void sequence_Causality(EObject context, Causality semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID code=ID)
	 */
	protected void sequence_Command(EObject context, Command semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, KanbanmodelPackage.Literals.COMMAND__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, KanbanmodelPackage.Literals.COMMAND__NAME));
			if(transientValues.isValueTransient(semanticObject, KanbanmodelPackage.Literals.COMMAND__CODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, KanbanmodelPackage.Literals.COMMAND__CODE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getCommandAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getCommandAccess().getCodeIDTerminalRuleCall_1_0(), semanticObject.getCode());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID (sdname=ID serviceProvisions+=Provision*)? entityBehavior=Statemachine)
	 */
	protected void sequence_Entity(EObject context, Entity semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID code=ID)
	 */
	protected void sequence_Event(EObject context, Event semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, KanbanmodelPackage.Literals.EVENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, KanbanmodelPackage.Literals.EVENT__NAME));
			if(transientValues.isValueTransient(semanticObject, KanbanmodelPackage.Literals.EVENT__CODE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, KanbanmodelPackage.Literals.EVENT__CODE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getEventAccess().getNameIDTerminalRuleCall_0_0(), semanticObject.getName());
		feeder.accept(grammarAccess.getEventAccess().getCodeIDTerminalRuleCall_1_0(), semanticObject.getCode());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         Mechanisms+=Mechanism? 
	 *         KSSSearchStrategies+=Strategy* 
	 *         (KSSTaskPatterns+=TaskPattern+ KSStaskPatternTypes+=TaskType+)? 
	 *         KSSValueFunctions+=ValueFunction* 
	 *         SoSServices+=ServiceType+ 
	 *         orgUnits+=ServiceProvider+ 
	 *         kssSources+=WorkSource+ 
	 *         kssWItems+=WorkItem+ 
	 *         replications=INT 
	 *         interArrivalTime=INT
	 *     )
	 */
	protected void sequence_KanbanSchedulingSystem(EObject context, KanbanSchedulingSystem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID caps+=Capability+)
	 */
	protected void sequence_KanbanTaskModel(EObject context, KanbanTaskModel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (owner=[ServiceProvider|ID] value=INT)
	 */
	protected void sequence_LocalValue(EObject context, LocalValue semanticObject) {
		if(errorAcceptor != null) {
			if(transientValues.isValueTransient(semanticObject, KanbanmodelPackage.Literals.LOCAL_VALUE__OWNER) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, KanbanmodelPackage.Literals.LOCAL_VALUE__OWNER));
			if(transientValues.isValueTransient(semanticObject, KanbanmodelPackage.Literals.LOCAL_VALUE__VALUE) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, KanbanmodelPackage.Literals.LOCAL_VALUE__VALUE));
		}
		INodesForEObjectProvider nodes = createNodeProvider(semanticObject);
		SequenceFeeder feeder = createSequencerFeeder(semanticObject, nodes);
		feeder.accept(grammarAccess.getLocalValueAccess().getOwnerServiceProviderIDTerminalRuleCall_0_1_0_1(), semanticObject.getOwner());
		feeder.accept(grammarAccess.getLocalValueAccess().getValueINTTerminalRuleCall_1_1_0(), semanticObject.getValue());
		feeder.finish();
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? processtype=STRING Strategies+=Strategy+)
	 */
	protected void sequence_Mechanism(EObject context, Mechanism semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (serviceName=[ServiceType|ID] providers+=[ServiceProvider|ID]*)
	 */
	protected void sequence_Provision(EObject context, Provision semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? rTasks+=[WorkItem|ID]+ dependencies+=Causality*)
	 */
	protected void sequence_Requirement(EObject context, Requirement semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_ResourceAllocation(EObject context, ResourceAllocation semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_ResourceOutsourcing(EObject context, ResourceOutsourcing semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? services+=Service*)
	 */
	protected void sequence_Resource(EObject context, Resource semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         description=STRING? 
	 *         sourceUnits+=[ServiceProvider|ID]* 
	 *         targetUnits+=[ServiceProvider|ID]* 
	 *         subordinateUnits+=[ServiceProvider|ID]* 
	 *         services+=Service* 
	 *         (
	 *             defaultStrategy=[Strategy|ID] 
	 *             (
	 *                 acceptanceRule=WIAcceptance? 
	 *                 selectionRule=WISelection? 
	 *                 assignmentRule=WIAssignment? 
	 *                 allocationRule=ResourceAllocation? 
	 *                 outsourcingRule=ResourceOutsourcing?
	 *             )?
	 *         )? 
	 *         resources+=Resource*
	 *     )
	 */
	protected void sequence_ServiceProvider(EObject context, ServiceProvider semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_ServiceType(EObject context, ServiceType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID (description=STRING? serviceType=[ServiceType|ID] efficiency=INT?)?)
	 */
	protected void sequence_Service(EObject context, Service semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_Skill(EObject context, Skill semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID actions+=[Command|ID]* transitions+=Transition*)
	 */
	protected void sequence_State(EObject context, State semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (events+=Event* commands+=Command* states+=State*)
	 */
	protected void sequence_Statemachine(EObject context, Statemachine semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         description=STRING? 
	 *         WIAcceptanceRule=WIAcceptance 
	 *         WISelectionRule=WISelection 
	 *         WIAssignmentRule=WIAssignment 
	 *         ResourceAllocationRule=ResourceAllocation 
	 *         ResourceOutsourcingRule=ResourceOutsourcing
	 *     )
	 */
	protected void sequence_Strategy(EObject context, Strategy semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? taskpatternTypes+=[TaskType|ID]*)
	 */
	protected void sequence_TaskPattern(EObject context, TaskPattern semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_TaskType(EObject context, TaskType semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     ((event=[Event|ID] state=[State|ID]) | (event=[Event|ID] eventactions+=[Command|ID]+ state=[State|ID]))
	 */
	protected void sequence_Transition(EObject context, Transition semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_ValueFunction(EObject context, ValueFunction semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? backlogQLimit=INT? readyQLimit=INT?)
	 */
	protected void sequence_WIAcceptance(EObject context, WIAcceptance semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_WIAssignment(EObject context, WIAssignment semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING?)
	 */
	protected void sequence_WISelection(EObject context, WISelection semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (
	 *         name=ID 
	 *         description=STRING? 
	 *         pattern=[TaskPattern|ID]? 
	 *         patternType=[TaskType|ID]? 
	 *         pTasks+=[WorkItem|ID]* 
	 *         sTasks+=[WorkItem|ID]* 
	 *         causalTriggers+=Causality* 
	 *         reqSpecialties+=[ServiceType|ID]* 
	 *         befforts=INT? 
	 *         bvalue=INT? 
	 *         lvalue+=LocalValue? 
	 *         COS=ID? 
	 *         wItemSource=[WorkSource|ID]? 
	 *         arrtime=INT? 
	 *         duedate=INT?
	 *     )
	 */
	protected void sequence_WorkItem(EObject context, WorkItem semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Constraint:
	 *     (name=ID description=STRING? targetUnits+=[ServiceProvider|ID]* assignmentRule=WIAssignment?)
	 */
	protected void sequence_WorkSource(EObject context, WorkSource semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
}
