/*
 * generated by Xtext
 */
package ausim.xtext.kanban.domainmodel.ui.contentassist

import ausim.xtext.kanban.domainmodel.ui.contentassist.AbstractKanbanmodelProposalProvider

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
class KanbanmodelProposalProvider extends AbstractKanbanmodelProposalProvider {
}
