/*
 * generated by Xtext
 */
package datasemModeller.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractDmodelValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(datasemModeller.dmodel.DmodelPackage.eINSTANCE);
		return result;
	}
}
